require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InventoryNeedsController do

  # This should return the minimal set of attributes required to create a valid
  # InventoryNeed. As you add validations to InventoryNeed, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "book_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InventoryNeedsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all inventory_needs as @inventory_needs" do
      inventory_need = InventoryNeed.create! valid_attributes
      get :index, {}, valid_session
      assigns(:inventory_needs).should eq([inventory_need])
    end
  end

  describe "GET show" do
    it "assigns the requested inventory_need as @inventory_need" do
      inventory_need = InventoryNeed.create! valid_attributes
      get :show, {:id => inventory_need.to_param}, valid_session
      assigns(:inventory_need).should eq(inventory_need)
    end
  end

  describe "GET new" do
    it "assigns a new inventory_need as @inventory_need" do
      get :new, {}, valid_session
      assigns(:inventory_need).should be_a_new(InventoryNeed)
    end
  end

  describe "GET edit" do
    it "assigns the requested inventory_need as @inventory_need" do
      inventory_need = InventoryNeed.create! valid_attributes
      get :edit, {:id => inventory_need.to_param}, valid_session
      assigns(:inventory_need).should eq(inventory_need)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InventoryNeed" do
        expect {
          post :create, {:inventory_need => valid_attributes}, valid_session
        }.to change(InventoryNeed, :count).by(1)
      end

      it "assigns a newly created inventory_need as @inventory_need" do
        post :create, {:inventory_need => valid_attributes}, valid_session
        assigns(:inventory_need).should be_a(InventoryNeed)
        assigns(:inventory_need).should be_persisted
      end

      it "redirects to the created inventory_need" do
        post :create, {:inventory_need => valid_attributes}, valid_session
        response.should redirect_to(InventoryNeed.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved inventory_need as @inventory_need" do
        # Trigger the behavior that occurs when invalid params are submitted
        InventoryNeed.any_instance.stub(:save).and_return(false)
        post :create, {:inventory_need => { "book_id" => "invalid value" }}, valid_session
        assigns(:inventory_need).should be_a_new(InventoryNeed)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InventoryNeed.any_instance.stub(:save).and_return(false)
        post :create, {:inventory_need => { "book_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested inventory_need" do
        inventory_need = InventoryNeed.create! valid_attributes
        # Assuming there are no other inventory_needs in the database, this
        # specifies that the InventoryNeed created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InventoryNeed.any_instance.should_receive(:update).with({ "book_id" => "1" })
        put :update, {:id => inventory_need.to_param, :inventory_need => { "book_id" => "1" }}, valid_session
      end

      it "assigns the requested inventory_need as @inventory_need" do
        inventory_need = InventoryNeed.create! valid_attributes
        put :update, {:id => inventory_need.to_param, :inventory_need => valid_attributes}, valid_session
        assigns(:inventory_need).should eq(inventory_need)
      end

      it "redirects to the inventory_need" do
        inventory_need = InventoryNeed.create! valid_attributes
        put :update, {:id => inventory_need.to_param, :inventory_need => valid_attributes}, valid_session
        response.should redirect_to(inventory_need)
      end
    end

    describe "with invalid params" do
      it "assigns the inventory_need as @inventory_need" do
        inventory_need = InventoryNeed.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InventoryNeed.any_instance.stub(:save).and_return(false)
        put :update, {:id => inventory_need.to_param, :inventory_need => { "book_id" => "invalid value" }}, valid_session
        assigns(:inventory_need).should eq(inventory_need)
      end

      it "re-renders the 'edit' template" do
        inventory_need = InventoryNeed.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InventoryNeed.any_instance.stub(:save).and_return(false)
        put :update, {:id => inventory_need.to_param, :inventory_need => { "book_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested inventory_need" do
      inventory_need = InventoryNeed.create! valid_attributes
      expect {
        delete :destroy, {:id => inventory_need.to_param}, valid_session
      }.to change(InventoryNeed, :count).by(-1)
    end

    it "redirects to the inventory_needs list" do
      inventory_need = InventoryNeed.create! valid_attributes
      delete :destroy, {:id => inventory_need.to_param}, valid_session
      response.should redirect_to(inventory_needs_url)
    end
  end

end
