require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InventoryHavesController do

  # This should return the minimal set of attributes required to create a valid
  # InventoryHave. As you add validations to InventoryHave, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "book_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InventoryHavesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all inventory_haves as @inventory_haves" do
      inventory_have = InventoryHave.create! valid_attributes
      get :index, {}, valid_session
      assigns(:inventory_haves).should eq([inventory_have])
    end
  end

  describe "GET show" do
    it "assigns the requested inventory_have as @inventory_have" do
      inventory_have = InventoryHave.create! valid_attributes
      get :show, {:id => inventory_have.to_param}, valid_session
      assigns(:inventory_have).should eq(inventory_have)
    end
  end

  describe "GET new" do
    it "assigns a new inventory_have as @inventory_have" do
      get :new, {}, valid_session
      assigns(:inventory_have).should be_a_new(InventoryHave)
    end
  end

  describe "GET edit" do
    it "assigns the requested inventory_have as @inventory_have" do
      inventory_have = InventoryHave.create! valid_attributes
      get :edit, {:id => inventory_have.to_param}, valid_session
      assigns(:inventory_have).should eq(inventory_have)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InventoryHave" do
        expect {
          post :create, {:inventory_have => valid_attributes}, valid_session
        }.to change(InventoryHave, :count).by(1)
      end

      it "assigns a newly created inventory_have as @inventory_have" do
        post :create, {:inventory_have => valid_attributes}, valid_session
        assigns(:inventory_have).should be_a(InventoryHave)
        assigns(:inventory_have).should be_persisted
      end

      it "redirects to the created inventory_have" do
        post :create, {:inventory_have => valid_attributes}, valid_session
        response.should redirect_to(InventoryHave.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved inventory_have as @inventory_have" do
        # Trigger the behavior that occurs when invalid params are submitted
        InventoryHave.any_instance.stub(:save).and_return(false)
        post :create, {:inventory_have => { "book_id" => "invalid value" }}, valid_session
        assigns(:inventory_have).should be_a_new(InventoryHave)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InventoryHave.any_instance.stub(:save).and_return(false)
        post :create, {:inventory_have => { "book_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested inventory_have" do
        inventory_have = InventoryHave.create! valid_attributes
        # Assuming there are no other inventory_haves in the database, this
        # specifies that the InventoryHave created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InventoryHave.any_instance.should_receive(:update).with({ "book_id" => "1" })
        put :update, {:id => inventory_have.to_param, :inventory_have => { "book_id" => "1" }}, valid_session
      end

      it "assigns the requested inventory_have as @inventory_have" do
        inventory_have = InventoryHave.create! valid_attributes
        put :update, {:id => inventory_have.to_param, :inventory_have => valid_attributes}, valid_session
        assigns(:inventory_have).should eq(inventory_have)
      end

      it "redirects to the inventory_have" do
        inventory_have = InventoryHave.create! valid_attributes
        put :update, {:id => inventory_have.to_param, :inventory_have => valid_attributes}, valid_session
        response.should redirect_to(inventory_have)
      end
    end

    describe "with invalid params" do
      it "assigns the inventory_have as @inventory_have" do
        inventory_have = InventoryHave.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InventoryHave.any_instance.stub(:save).and_return(false)
        put :update, {:id => inventory_have.to_param, :inventory_have => { "book_id" => "invalid value" }}, valid_session
        assigns(:inventory_have).should eq(inventory_have)
      end

      it "re-renders the 'edit' template" do
        inventory_have = InventoryHave.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InventoryHave.any_instance.stub(:save).and_return(false)
        put :update, {:id => inventory_have.to_param, :inventory_have => { "book_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested inventory_have" do
      inventory_have = InventoryHave.create! valid_attributes
      expect {
        delete :destroy, {:id => inventory_have.to_param}, valid_session
      }.to change(InventoryHave, :count).by(-1)
    end

    it "redirects to the inventory_haves list" do
      inventory_have = InventoryHave.create! valid_attributes
      delete :destroy, {:id => inventory_have.to_param}, valid_session
      response.should redirect_to(inventory_haves_url)
    end
  end

end
